//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBiblioCDsAudio.Properties.Vocabolury {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dict {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dict() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyBiblioCDsAudio.Properties.Vocabolury.Dict", typeof(Dict).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string barcodeGridview1 {
            get {
                return ResourceManager.GetString("barcodeGridview1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in Net.
        /// </summary>
        internal static string btninNet {
            get {
                return ResourceManager.GetString("btninNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string btnLocal {
            get {
                return ResourceManager.GetString("btnLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnsearch {
            get {
                return ResourceManager.GetString("btnsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string countryGridview1 {
            get {
                return ResourceManager.GetString("countryGridview1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover_Path.
        /// </summary>
        internal static string CoverPath {
            get {
                return ResourceManager.GetString("CoverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string dateGridview1 {
            get {
                return ResourceManager.GetString("dateGridview1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CD.
        /// </summary>
        internal static string dtgrvwInfoCd_ToolTipText_SelectCD {
            get {
                return ResourceManager.GetString("dtgrvwInfoCd_ToolTipText_SelectCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string editarTit_Artist {
            get {
                return ResourceManager.GetString("editarTit_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string editarTit_Title {
            get {
                return ResourceManager.GetString("editarTit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string editCover_File {
            get {
                return ResourceManager.GetString("editCover_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string editCover_Name {
            get {
                return ResourceManager.GetString("editCover_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size X:.
        /// </summary>
        internal static string editCover_SizeX {
            get {
                return ResourceManager.GetString("editCover_SizeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Y:.
        /// </summary>
        internal static string editCover_SizeY {
            get {
                return ResourceManager.GetString("editCover_SizeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists..
        /// </summary>
        internal static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string lbAlbum {
            get {
                return ResourceManager.GetString("lbAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string lbArtist {
            get {
                return ResourceManager.GetString("lbArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string lbBarcode {
            get {
                return ResourceManager.GetString("lbBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string lbCountry {
            get {
                return ResourceManager.GetString("lbCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lbDate {
            get {
                return ResourceManager.GetString("lbDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string lbFile {
            get {
                return ResourceManager.GetString("lbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string lbGenre {
            get {
                return ResourceManager.GetString("lbGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lbName {
            get {
                return ResourceManager.GetString("lbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Cover....
        /// </summary>
        internal static string lbSearchCover {
            get {
                return ResourceManager.GetString("lbSearchCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string lbSize {
            get {
                return ResourceManager.GetString("lbSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string lbTitle {
            get {
                return ResourceManager.GetString("lbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Menu.
        /// </summary>
        internal static string menuop {
            get {
                return ResourceManager.GetString("menuop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose this.
        /// </summary>
        internal static string mnChooseThis {
            get {
                return ResourceManager.GetString("mnChooseThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Info.
        /// </summary>
        internal static string mnEditInfo {
            get {
                return ResourceManager.GetString("mnEditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string mnFile {
            get {
                return ResourceManager.GetString("mnFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string mnSaveAS {
            get {
                return ResourceManager.GetString("mnSaveAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information not found in MusicBrainz for the CD.\nDo you want to manually enter Info: title, artist and restart the search?.
        /// </summary>
        internal static string msgbxCDnotFound {
            get {
                return ResourceManager.GetString("msgbxCDnotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD not found in MusicBrainz.
        /// </summary>
        internal static string msgbxcdnotfoundinMBrainz {
            get {
                return ResourceManager.GetString("msgbxcdnotfoundinMBrainz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD not found in MusicBrainz..
        /// </summary>
        internal static string msgCDNotFound {
            get {
                return ResourceManager.GetString("msgCDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information found about the CD. If the CD is your own compilation then select &quot;MYCOMPILATION&quot; from &quot;Media Type&quot; and then the CD driver..
        /// </summary>
        internal static string msgcdnotfoundAlternative {
            get {
                return ResourceManager.GetString("msgcdnotfoundAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication year too long.\nInsert or Correct.\nChoose &quot;Nos&quot; to save without the year..
        /// </summary>
        internal static string msgFormatDatencorrect {
            get {
                return ResourceManager.GetString("msgFormatDatencorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Genre.\nContinue?.
        /// </summary>
        internal static string msgGenreMiss {
            get {
                return ResourceManager.GetString("msgGenreMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter year.
        /// </summary>
        internal static string msgInsertJear {
            get {
                return ResourceManager.GetString("msgInsertJear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connection Problems..
        /// </summary>
        internal static string msgInternetConnection {
            get {
                return ResourceManager.GetString("msgInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or incorrect date.\nContinue?.
        /// </summary>
        internal static string msgMissngData {
            get {
                return ResourceManager.GetString("msgMissngData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist name not found: I continue without Name?.
        /// </summary>
        internal static string msgNameArtistNotFound {
            get {
                return ResourceManager.GetString("msgNameArtistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name was not found. Continue?.
        /// </summary>
        internal static string msgNameCDnotFound {
            get {
                return ResourceManager.GetString("msgNameCDnotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name Not Found:\nContinued without Name?.
        /// </summary>
        internal static string msgNameLandNotFound {
            get {
                return ResourceManager.GetString("msgNameLandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Problem.
        /// </summary>
        internal static string nameCapDate {
            get {
                return ResourceManager.GetString("nameCapDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Genre.
        /// </summary>
        internal static string nameCapGenre {
            get {
                return ResourceManager.GetString("nameCapGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Country.
        /// </summary>
        internal static string nameCaptionLand {
            get {
                return ResourceManager.GetString("nameCaptionLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Artist.
        /// </summary>
        internal static string nameCaptionmsgBox {
            get {
                return ResourceManager.GetString("nameCaptionmsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Title.
        /// </summary>
        internal static string nameCaptionTitle {
            get {
                return ResourceManager.GetString("nameCaptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist and Title.
        /// </summary>
        internal static string nameform {
            get {
                return ResourceManager.GetString("nameform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit info Cover.
        /// </summary>
        internal static string nameform2 {
            get {
                return ResourceManager.GetString("nameform2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release_ID.
        /// </summary>
        internal static string releaseidGridview1 {
            get {
                return ResourceManager.GetString("releaseidGridview1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string titleGridview1 {
            get {
                return ResourceManager.GetString("titleGridview1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Info.
        /// </summary>
        internal static string tpHideInfo {
            get {
                return ResourceManager.GetString("tpHideInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Info.
        /// </summary>
        internal static string tpshowInfo {
            get {
                return ResourceManager.GetString("tpshowInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click for zoom.
        /// </summary>
        internal static string tpZoom {
            get {
                return ResourceManager.GetString("tpZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string TrackDtGrVw_Duration {
            get {
                return ResourceManager.GetString("TrackDtGrVw_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TrackDtGrVw_Title {
            get {
                return ResourceManager.GetString("TrackDtGrVw_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tr.Num..
        /// </summary>
        internal static string TrackDtGrVw_TrNum {
            get {
                return ResourceManager.GetString("TrackDtGrVw_TrNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must Select One or More Cells or One or More Rows..
        /// </summary>
        internal static string w_OneMoreCellRows {
            get {
                return ResourceManager.GetString("w_OneMoreCellRows", resourceCulture);
            }
        }
    }
}
