//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBiblioCDs.Properties.Vocabolury {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dict {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dict() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyBiblioCDs.Properties.Vocabolury.Dict", typeof(Dict).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;ave Info.
        /// </summary>
        internal static string bntsaveInfo {
            get {
                return ResourceManager.GetString("bntsaveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List &amp;Files.
        /// </summary>
        internal static string btnListFiles {
            get {
                return ResourceManager.GetString("btnListFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string btnNote {
            get {
                return ResourceManager.GetString("btnNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnsave {
            get {
                return ResourceManager.GetString("btnsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        internal static string btnSaveAll {
            get {
                return ResourceManager.GetString("btnSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string btnStop {
            get {
                return ResourceManager.GetString("btnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string capInfo {
            get {
                return ResourceManager.GetString("capInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Include Autorun.
        /// </summary>
        internal static string ChkNotIncludeAutorun {
            get {
                return ResourceManager.GetString("ChkNotIncludeAutorun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Index.
        /// </summary>
        internal static string chkWordIndex {
            get {
                return ResourceManager.GetString("chkWordIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string frmt {
            get {
                return ResourceManager.GetString("frmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Name.
        /// </summary>
        internal static string lbCdName {
            get {
                return ResourceManager.GetString("lbCdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Number.
        /// </summary>
        internal static string lbCdNummer {
            get {
                return ResourceManager.GetString("lbCdNummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string lbCreationDate {
            get {
                return ResourceManager.GetString("lbCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Type.
        /// </summary>
        internal static string lbMediaType {
            get {
                return ResourceManager.GetString("lbMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos. CD.
        /// </summary>
        internal static string lbPosCD {
            get {
                return ResourceManager.GetString("lbPosCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Drive.
        /// </summary>
        internal static string lbSelectDrive {
            get {
                return ResourceManager.GetString("lbSelectDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Note.
        /// </summary>
        internal static string ldCdNote {
            get {
                return ResourceManager.GetString("ldCdNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string menuCancel {
            get {
                return ResourceManager.GetString("menuCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string menuEdit {
            get {
                return ResourceManager.GetString("menuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string menuFile {
            get {
                return ResourceManager.GetString("menuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MyBiblioCDs....
        /// </summary>
        internal static string menuitAbout {
            get {
                return ResourceManager.GetString("menuitAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string menuitExit {
            get {
                return ResourceManager.GetString("menuitExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string menuitLanguage {
            get {
                return ResourceManager.GetString("menuitLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string menuitNew {
            get {
                return ResourceManager.GetString("menuitNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        internal static string menuitSaveAll {
            get {
                return ResourceManager.GetString("menuitSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Info.
        /// </summary>
        internal static string menuitSaveInfo {
            get {
                return ResourceManager.GetString("menuitSaveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Preview.
        /// </summary>
        internal static string menuitSavePreview {
            get {
                return ResourceManager.GetString("menuitSavePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Explorer.
        /// </summary>
        internal static string menuitShowExplorer {
            get {
                return ResourceManager.GetString("menuitShowExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string menuTools {
            get {
                return ResourceManager.GetString("menuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD not found in MusicBrainz..
        /// </summary>
        internal static string msgCDNotFound {
            get {
                return ResourceManager.GetString("msgCDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Date Format.\nDo you want to fix it?. Format: \&quot;JJJJ:MM:DD\&quot;..
        /// </summary>
        internal static string msgFormatDatencorrect {
            get {
                return ResourceManager.GetString("msgFormatDatencorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Time Format.\n Format: \&quot;hh:mm:ss\&quot;..
        /// </summary>
        internal static string msgFormatTimeIncorrect {
            get {
                return ResourceManager.GetString("msgFormatTimeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Genre.\nContinue?.
        /// </summary>
        internal static string msgGenreMiss {
            get {
                return ResourceManager.GetString("msgGenreMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name to CD:.
        /// </summary>
        internal static string msgInsertCdName {
            get {
                return ResourceManager.GetString("msgInsertCdName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connection Problems..
        /// </summary>
        internal static string msgInternetConnection {
            get {
                return ResourceManager.GetString("msgInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Date.\nContinue?.
        /// </summary>
        internal static string msgMissngData {
            get {
                return ResourceManager.GetString("msgMissngData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist name not found: I continue without Name?.
        /// </summary>
        internal static string msgNameArtistNotFound {
            get {
                return ResourceManager.GetString("msgNameArtistNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name was not found. Continue?.
        /// </summary>
        internal static string msgNameCDnotFound {
            get {
                return ResourceManager.GetString("msgNameCDnotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name Not Found:\nContinued without Name?.
        /// </summary>
        internal static string msgNameLandNotFound {
            get {
                return ResourceManager.GetString("msgNameLandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems with DB connection..
        /// </summary>
        internal static string msgProblDBConnection {
            get {
                return ResourceManager.GetString("msgProblDBConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Exception.
        /// </summary>
        internal static string msgSecurityException {
            get {
                return ResourceManager.GetString("msgSecurityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key is probably locked.
        /// </summary>
        internal static string msgThekeyIsLocked {
            get {
                return ResourceManager.GetString("msgThekeyIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title CD not found.
        /// </summary>
        internal static string msgTitlenotFound {
            get {
                return ResourceManager.GetString("msgTitlenotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of tracks different between those found and present on the CD..
        /// </summary>
        internal static string msgTracksNum {
            get {
                return ResourceManager.GetString("msgTracksNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Access Exception.
        /// </summary>
        internal static string msgUnauthorizedAccessException {
            get {
                return ResourceManager.GetString("msgUnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing CD name.
        /// </summary>
        internal static string namCapCdMiss {
            get {
                return ResourceManager.GetString("namCapCdMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Problem.
        /// </summary>
        internal static string nameCapDate {
            get {
                return ResourceManager.GetString("nameCapDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Genre.
        /// </summary>
        internal static string nameCapGenre {
            get {
                return ResourceManager.GetString("nameCapGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Country.
        /// </summary>
        internal static string nameCaptionLand {
            get {
                return ResourceManager.GetString("nameCaptionLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Artist.
        /// </summary>
        internal static string nameCaptionmsgBox {
            get {
                return ResourceManager.GetString("nameCaptionmsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Title.
        /// </summary>
        internal static string nameCaptionTitle {
            get {
                return ResourceManager.GetString("nameCaptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save All.
        /// </summary>
        internal static string old_btnsaveAll {
            get {
                return ResourceManager.GetString("old_btnsaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is not working with the DB.
        /// </summary>
        internal static string ProblemDB {
            get {
                return ResourceManager.GetString("ProblemDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If something can go wrong, it will (Murphy).
        /// </summary>
        internal static string QUQ {
            get {
                return ResourceManager.GetString("QUQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Time Format.
        /// </summary>
        internal static string TimeError {
            get {
                return ResourceManager.GetString("TimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Info.
        /// </summary>
        internal static string toolpHideInfo {
            get {
                return ResourceManager.GetString("toolpHideInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List and Analyze Files.
        /// </summary>
        internal static string toolpListandAnalyzeFiles {
            get {
                return ResourceManager.GetString("toolpListandAnalyzeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click for zoom.
        /// </summary>
        internal static string toolpRightClickForZoom {
            get {
                return ResourceManager.GetString("toolpRightClickForZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the CD Number, CD Notes, Location and Title.
        /// </summary>
        internal static string toolpSavesInfo {
            get {
                return ResourceManager.GetString("toolpSavesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Info.
        /// </summary>
        internal static string toolpShowInfo {
            get {
                return ResourceManager.GetString("toolpShowInfo", resourceCulture);
            }
        }
    }
}
